FROM setsoft/kicad_auto:nightly
MAINTAINER Salvador E. Tropea <set@ieee.org>
LABEL Description="KiCad with KiBot and other automation scripts w/test tools"

COPY *.deb /
RUN     apt-get update  && \
	apt-get -y install --no-install-recommends flake8 \
	                                           python3-pytest \
	                                           python3-coverage \
	                                           imagemagick librsvg2-bin ghostscript \
	                                           diffutils git \
	                                           x11-utils fluxbox x11vnc wmctrl \
	                                           unzip && \
	apt -y install --no-install-recommends ./*.deb && \
	apt-get -y autoremove && \
	rm -rf /var/lib/apt/lists/*

