FROM setsoft/kicad_auto:nightly
MAINTAINER Salvador E. Tropea <set@ieee.org>
LABEL Description="KiCad with KiBot and other automation scripts w/test tools"

RUN     apt-get update  && \
	apt-get -y install --no-install-recommends flake8 \
	                                           python3-pytest \
	                                           python3-coverage \
	                                           imagemagick librsvg2-bin ghostscript \
	                                           diffutils git \
	                                           x11-utils fluxbox x11vnc wmctrl \
	                                           unzip \
	                                           procps && \
	apt-get -y install wget curl && \
	curl -s https://api.github.com/repos/set-soft/coveralls-python/releases/latest | grep "browser_download_url.*deb" | cut -d : -f 2,3 | tr -d \" | wget -i - && \
	apt -y install --no-install-recommends ./*.deb && \
	rm *.deb && \
	apt-get -y remove curl wget && \
	apt-get -y autoremove && \
	rm -rf /var/lib/apt/lists/*

