FROM ghcr.io/inti-cmnb/kicad_debian:nightly_full
LABEL Maintainer="Salvador E. Tropea <set@ieee.org>"
LABEL Description="Layer used for new dependencies"
LABEL org.opencontainers.image.description="Layer used for new dependencies"

